// Define enums since they might not be exported properly
enum WorkflowDifficulty {
  beginner = 'beginner',
  intermediate = 'intermediate',
  advanced = 'advanced',
  expert = 'expert'
}

enum WorkflowStatus {
  draft = 'draft',
  published = 'published',
  archived = 'archived'
}

// Extended workflow data - 100+ workflows across different categories
export const extendedWorkflows = [
  // Content Creation Workflows
  {
    slug: 'viral-tweet-thread-generator',
    name: 'Viral Twitter Thread Generator',
    nameZh: '病毒式推特帖子生成器',
    description: 'Create engaging Twitter threads that maximize reach and engagement',
    descriptionZh: '创建能够最大化传播和互动的推特话题帖',
    categorySlug: 'content-creation',
    subcategory: 'Social Media',
    tags: ['twitter', 'social-media', 'viral', 'content'],
    difficulty: WorkflowDifficulty.beginner,
    estimatedTimeLearning: 10,
    estimatedTimeExecution: 20,
    monthlyCost: 40,
    perUseCost: 1.5,
    status: WorkflowStatus.published,
    featured: false,
  },
  {
    slug: 'linkedin-article-optimizer',
    name: 'LinkedIn Article Optimization Pipeline',
    nameZh: 'LinkedIn文章优化流程',
    description: 'Transform your ideas into LinkedIn articles that drive professional engagement',
    descriptionZh: '将您的想法转化为能够推动专业互动的LinkedIn文章',
    categorySlug: 'content-creation',
    subcategory: 'Professional Writing',
    tags: ['linkedin', 'professional', 'article', 'b2b'],
    difficulty: WorkflowDifficulty.intermediate,
    estimatedTimeLearning: 25,
    estimatedTimeExecution: 45,
    monthlyCost: 55,
    perUseCost: 2.8,
    status: WorkflowStatus.published,
    featured: false,
  },
  {
    slug: 'podcast-show-notes-automation',
    name: 'Automated Podcast Show Notes Creator',
    nameZh: '自动播客节目笔记创建器',
    description: 'Generate comprehensive show notes, timestamps, and summaries from podcast audio',
    descriptionZh: '从播客音频生成全面的节目笔记、时间戳和摘要',
    categorySlug: 'content-creation',
    subcategory: 'Podcast',
    tags: ['podcast', 'audio', 'transcription', 'notes'],
    difficulty: WorkflowDifficulty.intermediate,
    estimatedTimeLearning: 30,
    estimatedTimeExecution: 60,
    monthlyCost: 75,
    perUseCost: 4,
    status: WorkflowStatus.published,
    featured: true,
  },
  {
    slug: 'ebook-creation-pipeline',
    name: 'Complete eBook Creation Pipeline',
    nameZh: '完整电子书创作流程',
    description: 'From outline to formatted eBook with cover design in one workflow',
    descriptionZh: '从大纲到带封面设计的格式化电子书的一站式工作流',
    categorySlug: 'content-creation',
    subcategory: 'Long-form Content',
    tags: ['ebook', 'writing', 'publishing', 'design'],
    difficulty: WorkflowDifficulty.advanced,
    estimatedTimeLearning: 60,
    estimatedTimeExecution: 240,
    monthlyCost: 95,
    perUseCost: 12,
    status: WorkflowStatus.published,
    featured: false,
  },
  {
    slug: 'newsletter-automation-system',
    name: 'Weekly Newsletter Automation System',
    nameZh: '每周通讯自动化系统',
    description: 'Curate, write, and design professional newsletters automatically',
    descriptionZh: '自动策划、撰写和设计专业通讯',
    categorySlug: 'content-creation',
    subcategory: 'Email Marketing',
    tags: ['newsletter', 'email', 'automation', 'marketing'],
    difficulty: WorkflowDifficulty.intermediate,
    estimatedTimeLearning: 35,
    estimatedTimeExecution: 90,
    monthlyCost: 65,
    perUseCost: 3.5,
    status: WorkflowStatus.published,
    featured: false,
  },

  // Video Production Workflows
  {
    slug: 'youtube-shorts-factory',
    name: 'YouTube Shorts Factory',
    nameZh: 'YouTube短视频工厂',
    description: 'Mass produce engaging YouTube Shorts from long-form content',
    descriptionZh: '从长视频内容批量生产吸引人的YouTube短视频',
    categorySlug: 'video-production',
    subcategory: 'Short-form Video',
    tags: ['youtube', 'shorts', 'video', 'viral'],
    difficulty: WorkflowDifficulty.intermediate,
    estimatedTimeLearning: 40,
    estimatedTimeExecution: 120,
    monthlyCost: 85,
    perUseCost: 5,
    status: WorkflowStatus.published,
    featured: true,
  },
  {
    slug: 'tiktok-content-repurposing',
    name: 'TikTok Content Repurposing Machine',
    nameZh: 'TikTok内容再利用机器',
    description: 'Transform existing content into TikTok-ready videos with trending effects',
    descriptionZh: '将现有内容转换为带有流行效果的TikTok视频',
    categorySlug: 'video-production',
    subcategory: 'Social Media Video',
    tags: ['tiktok', 'social-media', 'repurposing', 'trending'],
    difficulty: WorkflowDifficulty.beginner,
    estimatedTimeLearning: 20,
    estimatedTimeExecution: 30,
    monthlyCost: 50,
    perUseCost: 2.5,
    status: WorkflowStatus.published,
    featured: false,
  },
  {
    slug: 'ai-avatar-video-presenter',
    name: 'AI Avatar Video Presenter',
    nameZh: 'AI虚拟主播视频制作',
    description: 'Create professional presentations with AI avatars in multiple languages',
    descriptionZh: '使用AI虚拟形象创建多语言专业演示视频',
    categorySlug: 'video-production',
    subcategory: 'Avatar Videos',
    tags: ['avatar', 'presentation', 'multilingual', 'ai-presenter'],
    difficulty: WorkflowDifficulty.beginner,
    estimatedTimeLearning: 15,
    estimatedTimeExecution: 25,
    monthlyCost: 60,
    perUseCost: 3,
    status: WorkflowStatus.published,
    featured: false,
  },
  {
    slug: 'documentary-style-video-creator',
    name: 'Documentary-Style Video Creator',
    nameZh: '纪录片风格视频创作器',
    description: 'Produce professional documentary videos with narration and b-roll',
    descriptionZh: '制作带有旁白和补充镜头的专业纪录片视频',
    categorySlug: 'video-production',
    subcategory: 'Long-form Video',
    tags: ['documentary', 'storytelling', 'professional', 'long-form'],
    difficulty: WorkflowDifficulty.advanced,
    estimatedTimeLearning: 90,
    estimatedTimeExecution: 360,
    monthlyCost: 150,
    perUseCost: 20,
    status: WorkflowStatus.published,
    featured: false,
  },
  {
    slug: 'instagram-reels-optimizer',
    name: 'Instagram Reels Optimization Suite',
    nameZh: 'Instagram Reels优化套件',
    description: 'Create and optimize Reels for maximum Instagram algorithm performance',
    descriptionZh: '创建并优化Reels以获得最佳Instagram算法表现',
    categorySlug: 'video-production',
    subcategory: 'Social Media Video',
    tags: ['instagram', 'reels', 'optimization', 'algorithm'],
    difficulty: WorkflowDifficulty.intermediate,
    estimatedTimeLearning: 30,
    estimatedTimeExecution: 45,
    monthlyCost: 70,
    perUseCost: 3.5,
    status: WorkflowStatus.published,
    featured: false,
  },

  // Web Development Workflows
  {
    slug: 'saas-mvp-builder',
    name: 'SaaS MVP Builder',
    nameZh: 'SaaS MVP构建器',
    description: 'Build a functional SaaS MVP with authentication and payments',
    descriptionZh: '构建带有身份验证和支付功能的SaaS MVP',
    categorySlug: 'web-development',
    subcategory: 'Full-stack',
    tags: ['saas', 'mvp', 'full-stack', 'startup'],
    difficulty: WorkflowDifficulty.advanced,
    estimatedTimeLearning: 120,
    estimatedTimeExecution: 480,
    monthlyCost: 100,
    perUseCost: 25,
    status: WorkflowStatus.published,
    featured: true,
  },
  {
    slug: 'ecommerce-store-generator',
    name: 'E-commerce Store Generator',
    nameZh: '电商商店生成器',
    description: 'Create a complete e-commerce store with product listings and checkout',
    descriptionZh: '创建包含产品列表和结账功能的完整电商商店',
    categorySlug: 'web-development',
    subcategory: 'E-commerce',
    tags: ['ecommerce', 'store', 'shopping', 'payments'],
    difficulty: WorkflowDifficulty.intermediate,
    estimatedTimeLearning: 60,
    estimatedTimeExecution: 180,
    monthlyCost: 80,
    perUseCost: 15,
    status: WorkflowStatus.published,
    featured: false,
  },
  {
    slug: 'api-documentation-generator',
    name: 'Interactive API Documentation',
    nameZh: '交互式API文档生成器',
    description: 'Generate beautiful, interactive API documentation from code',
    descriptionZh: '从代码生成美观的交互式API文档',
    categorySlug: 'web-development',
    subcategory: 'Documentation',
    tags: ['api', 'documentation', 'developer-tools', 'automation'],
    difficulty: WorkflowDifficulty.intermediate,
    estimatedTimeLearning: 40,
    estimatedTimeExecution: 90,
    monthlyCost: 45,
    perUseCost: 5,
    status: WorkflowStatus.published,
    featured: false,
  },
  {
    slug: 'portfolio-website-builder',
    name: 'Portfolio Website Builder',
    nameZh: '作品集网站构建器',
    description: 'Create stunning portfolio websites with animations and interactions',
    descriptionZh: '创建带有动画和交互效果的精美作品集网站',
    categorySlug: 'web-development',
    subcategory: 'Portfolio',
    tags: ['portfolio', 'personal-brand', 'showcase', 'creative'],
    difficulty: WorkflowDifficulty.beginner,
    estimatedTimeLearning: 30,
    estimatedTimeExecution: 120,
    monthlyCost: 35,
    perUseCost: 8,
    status: WorkflowStatus.published,
    featured: false,
  },
  {
    slug: 'pwa-app-converter',
    name: 'PWA App Converter',
    nameZh: 'PWA应用转换器',
    description: 'Convert any website into a Progressive Web App with offline support',
    descriptionZh: '将任何网站转换为支持离线功能的渐进式Web应用',
    categorySlug: 'web-development',
    subcategory: 'Mobile Web',
    tags: ['pwa', 'mobile', 'offline', 'performance'],
    difficulty: WorkflowDifficulty.intermediate,
    estimatedTimeLearning: 45,
    estimatedTimeExecution: 150,
    monthlyCost: 40,
    perUseCost: 10,
    status: WorkflowStatus.published,
    featured: false,
  },

  // Data Analysis Workflows
  {
    slug: 'market-research-analyzer',
    name: 'AI Market Research Analyzer',
    nameZh: 'AI市场研究分析器',
    description: 'Comprehensive market analysis with competitor insights and trends',
    descriptionZh: '包含竞争对手洞察和趋势的全面市场分析',
    categorySlug: 'data-analysis',
    subcategory: 'Market Research',
    tags: ['market-research', 'analysis', 'competitive', 'insights'],
    difficulty: WorkflowDifficulty.intermediate,
    estimatedTimeLearning: 50,
    estimatedTimeExecution: 180,
    monthlyCost: 90,
    perUseCost: 12,
    status: WorkflowStatus.published,
    featured: true,
  },
  {
    slug: 'sales-forecasting-model',
    name: 'Sales Forecasting Model Builder',
    nameZh: '销售预测模型构建器',
    description: 'Build accurate sales forecasting models with AI-powered predictions',
    descriptionZh: '使用AI预测构建准确的销售预测模型',
    categorySlug: 'data-analysis',
    subcategory: 'Predictive Analytics',
    tags: ['sales', 'forecasting', 'predictive', 'business'],
    difficulty: WorkflowDifficulty.advanced,
    estimatedTimeLearning: 80,
    estimatedTimeExecution: 240,
    monthlyCost: 120,
    perUseCost: 18,
    status: WorkflowStatus.published,
    featured: false,
  },
  {
    slug: 'customer-sentiment-analyzer',
    name: 'Customer Sentiment Analysis Suite',
    nameZh: '客户情感分析套件',
    description: 'Analyze customer feedback across all channels for actionable insights',
    descriptionZh: '分析所有渠道的客户反馈以获得可操作的洞察',
    categorySlug: 'data-analysis',
    subcategory: 'Customer Analytics',
    tags: ['sentiment', 'customer', 'feedback', 'nlp'],
    difficulty: WorkflowDifficulty.intermediate,
    estimatedTimeLearning: 40,
    estimatedTimeExecution: 120,
    monthlyCost: 85,
    perUseCost: 10,
    status: WorkflowStatus.published,
    featured: false,
  },
  {
    slug: 'financial-report-automation',
    name: 'Financial Report Automation',
    nameZh: '财务报告自动化',
    description: 'Generate comprehensive financial reports with visualizations',
    descriptionZh: '生成带有可视化的综合财务报告',
    categorySlug: 'data-analysis',
    subcategory: 'Financial Analysis',
    tags: ['finance', 'reporting', 'automation', 'visualization'],
    difficulty: WorkflowDifficulty.advanced,
    estimatedTimeLearning: 90,
    estimatedTimeExecution: 180,
    monthlyCost: 150,
    perUseCost: 20,
    status: WorkflowStatus.published,
    featured: false,
  },
  {
    slug: 'social-media-analytics',
    name: 'Social Media Analytics Dashboard',
    nameZh: '社交媒体分析仪表板',
    description: 'Track and analyze social media performance across all platforms',
    descriptionZh: '跟踪和分析所有平台的社交媒体表现',
    categorySlug: 'data-analysis',
    subcategory: 'Social Analytics',
    tags: ['social-media', 'analytics', 'tracking', 'performance'],
    difficulty: WorkflowDifficulty.intermediate,
    estimatedTimeLearning: 45,
    estimatedTimeExecution: 90,
    monthlyCost: 75,
    perUseCost: 8,
    status: WorkflowStatus.published,
    featured: false,
  },

  // Design Work Workflows
  {
    slug: 'brand-identity-creator',
    name: 'Complete Brand Identity Creator',
    nameZh: '完整品牌形象创建器',
    description: 'Design complete brand identity including logo, colors, and guidelines',
    descriptionZh: '设计包括标志、颜色和指南的完整品牌形象',
    categorySlug: 'design-work',
    subcategory: 'Branding',
    tags: ['branding', 'logo', 'identity', 'guidelines'],
    difficulty: WorkflowDifficulty.intermediate,
    estimatedTimeLearning: 60,
    estimatedTimeExecution: 240,
    monthlyCost: 85,
    perUseCost: 15,
    status: WorkflowStatus.published,
    featured: true,
  },
  {
    slug: 'ui-design-system-generator',
    name: 'UI Design System Generator',
    nameZh: 'UI设计系统生成器',
    description: 'Create comprehensive UI design systems with components and documentation',
    descriptionZh: '创建包含组件和文档的综合UI设计系统',
    categorySlug: 'design-work',
    subcategory: 'UI/UX',
    tags: ['ui', 'design-system', 'components', 'figma'],
    difficulty: WorkflowDifficulty.advanced,
    estimatedTimeLearning: 90,
    estimatedTimeExecution: 360,
    monthlyCost: 95,
    perUseCost: 20,
    status: WorkflowStatus.published,
    featured: false,
  },
  {
    slug: 'social-media-template-pack',
    name: 'Social Media Template Pack Creator',
    nameZh: '社交媒体模板包创建器',
    description: 'Design consistent social media templates for all platforms',
    descriptionZh: '为所有平台设计一致的社交媒体模板',
    categorySlug: 'design-work',
    subcategory: 'Social Media Design',
    tags: ['templates', 'social-media', 'consistency', 'branding'],
    difficulty: WorkflowDifficulty.beginner,
    estimatedTimeLearning: 30,
    estimatedTimeExecution: 90,
    monthlyCost: 55,
    perUseCost: 8,
    status: WorkflowStatus.published,
    featured: false,
  },
  {
    slug: 'infographic-automation',
    name: 'Data-Driven Infographic Creator',
    nameZh: '数据驱动信息图创建器',
    description: 'Transform data into beautiful, shareable infographics automatically',
    descriptionZh: '自动将数据转换为美观、可分享的信息图',
    categorySlug: 'design-work',
    subcategory: 'Data Visualization',
    tags: ['infographic', 'data-viz', 'visual-content', 'shareworthy'],
    difficulty: WorkflowDifficulty.intermediate,
    estimatedTimeLearning: 40,
    estimatedTimeExecution: 60,
    monthlyCost: 65,
    perUseCost: 5,
    status: WorkflowStatus.published,
    featured: false,
  },
  {
    slug: 'product-mockup-generator',
    name: 'Product Mockup Generator',
    nameZh: '产品样机生成器',
    description: 'Create realistic product mockups for marketing and presentations',
    descriptionZh: '为营销和演示创建逼真的产品样机',
    categorySlug: 'design-work',
    subcategory: 'Product Design',
    tags: ['mockup', 'product', 'marketing', '3d'],
    difficulty: WorkflowDifficulty.beginner,
    estimatedTimeLearning: 20,
    estimatedTimeExecution: 30,
    monthlyCost: 45,
    perUseCost: 3,
    status: WorkflowStatus.published,
    featured: false,
  },

  // Marketing Workflows
  {
    slug: 'influencer-outreach-automation',
    name: 'Influencer Outreach Automation',
    nameZh: '网红推广自动化',
    description: 'Find and reach out to relevant influencers at scale',
    descriptionZh: '大规模寻找并联系相关网红',
    categorySlug: 'marketing',
    subcategory: 'Influencer Marketing',
    tags: ['influencer', 'outreach', 'automation', 'scale'],
    difficulty: WorkflowDifficulty.intermediate,
    estimatedTimeLearning: 45,
    estimatedTimeExecution: 120,
    monthlyCost: 95,
    perUseCost: 10,
    status: WorkflowStatus.published,
    featured: true,
  },
  {
    slug: 'email-campaign-optimizer',
    name: 'Email Campaign Optimization Suite',
    nameZh: '邮件营销优化套件',
    description: 'A/B test and optimize email campaigns for maximum conversion',
    descriptionZh: 'A/B测试并优化邮件营销以获得最大转化',
    categorySlug: 'marketing',
    subcategory: 'Email Marketing',
    tags: ['email', 'ab-testing', 'optimization', 'conversion'],
    difficulty: WorkflowDifficulty.intermediate,
    estimatedTimeLearning: 50,
    estimatedTimeExecution: 150,
    monthlyCost: 80,
    perUseCost: 12,
    status: WorkflowStatus.published,
    featured: false,
  },
  {
    slug: 'content-calendar-generator',
    name: 'Content Calendar Generator',
    nameZh: '内容日历生成器',
    description: 'Create month-long content calendars with post ideas and copy',
    descriptionZh: '创建包含帖子创意和文案的月度内容日历',
    categorySlug: 'marketing',
    subcategory: 'Content Planning',
    tags: ['calendar', 'planning', 'content', 'strategy'],
    difficulty: WorkflowDifficulty.beginner,
    estimatedTimeLearning: 25,
    estimatedTimeExecution: 60,
    monthlyCost: 55,
    perUseCost: 5,
    status: WorkflowStatus.published,
    featured: false,
  },
  {
    slug: 'competitor-monitoring-system',
    name: 'Competitor Monitoring System',
    nameZh: '竞争对手监控系统',
    description: 'Track competitor activities and get actionable insights',
    descriptionZh: '跟踪竞争对手活动并获得可操作的洞察',
    categorySlug: 'marketing',
    subcategory: 'Competitive Intelligence',
    tags: ['competitor', 'monitoring', 'intelligence', 'tracking'],
    difficulty: WorkflowDifficulty.advanced,
    estimatedTimeLearning: 70,
    estimatedTimeExecution: 180,
    monthlyCost: 120,
    perUseCost: 15,
    status: WorkflowStatus.published,
    featured: false,
  },
  {
    slug: 'lead-generation-machine',
    name: 'B2B Lead Generation Machine',
    nameZh: 'B2B潜在客户生成器',
    description: 'Automate B2B lead generation with qualification and outreach',
    descriptionZh: '自动化B2B潜在客户生成，包括资格审查和推广',
    categorySlug: 'marketing',
    subcategory: 'Lead Generation',
    tags: ['b2b', 'leads', 'automation', 'sales'],
    difficulty: WorkflowDifficulty.intermediate,
    estimatedTimeLearning: 55,
    estimatedTimeExecution: 180,
    monthlyCost: 110,
    perUseCost: 14,
    status: WorkflowStatus.published,
    featured: false,
  },

  // Productivity Workflows
  {
    slug: 'meeting-minutes-automation',
    name: 'Automated Meeting Minutes',
    nameZh: '自动会议记录',
    description: 'Generate comprehensive meeting minutes with action items',
    descriptionZh: '生成包含行动项的综合会议记录',
    categorySlug: 'productivity',
    subcategory: 'Meeting Management',
    tags: ['meetings', 'minutes', 'automation', 'productivity'],
    difficulty: WorkflowDifficulty.beginner,
    estimatedTimeLearning: 15,
    estimatedTimeExecution: 15,
    monthlyCost: 35,
    perUseCost: 2,
    status: WorkflowStatus.published,
    featured: false,
  },
  {
    slug: 'knowledge-base-builder',
    name: 'AI Knowledge Base Builder',
    nameZh: 'AI知识库构建器',
    description: 'Build searchable knowledge bases from documents and conversations',
    descriptionZh: '从文档和对话构建可搜索的知识库',
    categorySlug: 'productivity',
    subcategory: 'Knowledge Management',
    tags: ['knowledge-base', 'documentation', 'search', 'ai'],
    difficulty: WorkflowDifficulty.intermediate,
    estimatedTimeLearning: 40,
    estimatedTimeExecution: 120,
    monthlyCost: 65,
    perUseCost: 8,
    status: WorkflowStatus.published,
    featured: false,
  },
  {
    slug: 'task-automation-system',
    name: 'Smart Task Automation System',
    nameZh: '智能任务自动化系统',
    description: 'Automate repetitive tasks across multiple apps and services',
    descriptionZh: '跨多个应用和服务自动化重复任务',
    categorySlug: 'productivity',
    subcategory: 'Task Management',
    tags: ['automation', 'tasks', 'workflow', 'integration'],
    difficulty: WorkflowDifficulty.intermediate,
    estimatedTimeLearning: 50,
    estimatedTimeExecution: 90,
    monthlyCost: 75,
    perUseCost: 6,
    status: WorkflowStatus.published,
    featured: true,
  },
  {
    slug: 'document-summarizer',
    name: 'Intelligent Document Summarizer',
    nameZh: '智能文档摘要器',
    description: 'Summarize long documents into key insights and action items',
    descriptionZh: '将长文档总结为关键洞察和行动项',
    categorySlug: 'productivity',
    subcategory: 'Document Processing',
    tags: ['summarization', 'documents', 'insights', 'time-saving'],
    difficulty: WorkflowDifficulty.beginner,
    estimatedTimeLearning: 10,
    estimatedTimeExecution: 10,
    monthlyCost: 25,
    perUseCost: 1,
    status: WorkflowStatus.published,
    featured: false,
  },
  {
    slug: 'email-inbox-manager',
    name: 'AI Email Inbox Manager',
    nameZh: 'AI邮件收件箱管理器',
    description: 'Automatically categorize, prioritize, and draft responses to emails',
    descriptionZh: '自动分类、优先排序和起草邮件回复',
    categorySlug: 'productivity',
    subcategory: 'Email Management',
    tags: ['email', 'inbox', 'management', 'ai-assistant'],
    difficulty: WorkflowDifficulty.intermediate,
    estimatedTimeLearning: 35,
    estimatedTimeExecution: 60,
    monthlyCost: 55,
    perUseCost: 4,
    status: WorkflowStatus.published,
    featured: false,
  },

  // Education Workflows
  {
    slug: 'course-creation-suite',
    name: 'Complete Course Creation Suite',
    nameZh: '完整课程创建套件',
    description: 'Create comprehensive online courses with videos, quizzes, and materials',
    descriptionZh: '创建包含视频、测验和材料的综合在线课程',
    categorySlug: 'education',
    subcategory: 'Course Creation',
    tags: ['course', 'education', 'online-learning', 'content'],
    difficulty: WorkflowDifficulty.advanced,
    estimatedTimeLearning: 120,
    estimatedTimeExecution: 480,
    monthlyCost: 125,
    perUseCost: 25,
    status: WorkflowStatus.published,
    featured: true,
  },
  {
    slug: 'study-guide-generator',
    name: 'AI Study Guide Generator',
    nameZh: 'AI学习指南生成器',
    description: 'Generate personalized study guides from textbooks and lectures',
    descriptionZh: '从教科书和讲座生成个性化学习指南',
    categorySlug: 'education',
    subcategory: 'Study Materials',
    tags: ['study', 'education', 'personalized', 'learning'],
    difficulty: WorkflowDifficulty.beginner,
    estimatedTimeLearning: 20,
    estimatedTimeExecution: 30,
    monthlyCost: 40,
    perUseCost: 2,
    status: WorkflowStatus.published,
    featured: false,
  },
  {
    slug: 'quiz-question-bank',
    name: 'Quiz Question Bank Builder',
    nameZh: '测验题库构建器',
    description: 'Create comprehensive question banks with various difficulty levels',
    descriptionZh: '创建包含不同难度级别的综合题库',
    categorySlug: 'education',
    subcategory: 'Assessment',
    tags: ['quiz', 'assessment', 'questions', 'testing'],
    difficulty: WorkflowDifficulty.intermediate,
    estimatedTimeLearning: 40,
    estimatedTimeExecution: 90,
    monthlyCost: 50,
    perUseCost: 5,
    status: WorkflowStatus.published,
    featured: false,
  },
  {
    slug: 'language-learning-assistant',
    name: 'AI Language Learning Assistant',
    nameZh: 'AI语言学习助手',
    description: 'Personalized language learning with conversation practice and feedback',
    descriptionZh: '带有对话练习和反馈的个性化语言学习',
    categorySlug: 'education',
    subcategory: 'Language Learning',
    tags: ['language', 'learning', 'conversation', 'practice'],
    difficulty: WorkflowDifficulty.intermediate,
    estimatedTimeLearning: 30,
    estimatedTimeExecution: 60,
    monthlyCost: 60,
    perUseCost: 3,
    status: WorkflowStatus.published,
    featured: false,
  },
  {
    slug: 'research-paper-assistant',
    name: 'Research Paper Writing Assistant',
    nameZh: '研究论文写作助手',
    description: 'Help write academic papers with citations and proper formatting',
    descriptionZh: '帮助撰写带有引用和正确格式的学术论文',
    categorySlug: 'education',
    subcategory: 'Academic Writing',
    tags: ['research', 'academic', 'writing', 'citations'],
    difficulty: WorkflowDifficulty.advanced,
    estimatedTimeLearning: 60,
    estimatedTimeExecution: 240,
    monthlyCost: 85,
    perUseCost: 10,
    status: WorkflowStatus.published,
    featured: false,
  },
]

// Extended workflow steps for new workflows
export const extendedWorkflowSteps = {
  'viral-tweet-thread-generator': [
    {
      stepOrder: 1,
      title: 'Topic Research & Trending Analysis',
      titleZh: '话题研究与趋势分析',
      description: 'Analyze trending topics and viral patterns',
      descriptionZh: '分析热门话题和病毒式传播模式',
      estimatedTime: 5,
      primaryToolName: 'Perplexity',
      primaryToolSlug: 'perplexity',
      primaryToolLogoUrl: 'https://pplx-res.cloudinary.com/image/upload/v1705076612/website-assets/favicon-194x194_clneeu.png',
      alternativeToolNames: ['ChatGPT', 'Claude'],
    },
    {
      stepOrder: 2,
      title: 'Thread Content Generation',
      titleZh: '帖子内容生成',
      description: 'Create engaging thread content with hooks',
      descriptionZh: '创建带有吸引力的帖子内容',
      estimatedTime: 10,
      primaryToolName: 'Claude',
      primaryToolSlug: 'claude',
      primaryToolLogoUrl: 'https://www.anthropic.com/images/icons/apple-touch-icon.png',
      alternativeToolNames: ['ChatGPT', 'Jasper'],
    },
    {
      stepOrder: 3,
      title: 'Visual Content Creation',
      titleZh: '视觉内容创建',
      description: 'Generate eye-catching visuals for threads',
      descriptionZh: '为帖子生成吸引眼球的视觉内容',
      estimatedTime: 5,
      primaryToolName: 'Canva',
      primaryToolSlug: 'canva',
      primaryToolLogoUrl: 'https://www.canva.com/favicon.ico',
      alternativeToolNames: ['Midjourney', 'DALL-E'],
    },
  ],
  'youtube-shorts-factory': [
    {
      stepOrder: 1,
      title: 'Long-form Content Analysis',
      titleZh: '长视频内容分析',
      description: 'Identify key moments and highlights',
      descriptionZh: '识别关键时刻和亮点',
      estimatedTime: 20,
      primaryToolName: 'Descript',
      primaryToolSlug: 'descript',
      primaryToolLogoUrl: 'https://www.descript.com/favicon.ico',
      alternativeToolNames: ['Otter', 'Trint'],
    },
    {
      stepOrder: 2,
      title: 'Short Clip Extraction',
      titleZh: '短片段提取',
      description: 'Extract and edit short clips',
      descriptionZh: '提取和编辑短片段',
      estimatedTime: 40,
      primaryToolName: 'Runway',
      primaryToolSlug: 'runway',
      primaryToolLogoUrl: 'https://assets-global.website-files.com/62e0e9ced95e1e13a67378a2/6304c0bf7e0b086647d7eb1f_favicon-256x256.png',
      alternativeToolNames: ['CapCut', 'InVideo'],
    },
    {
      stepOrder: 3,
      title: 'Caption & Effects',
      titleZh: '字幕和效果',
      description: 'Add captions and trending effects',
      descriptionZh: '添加字幕和流行效果',
      estimatedTime: 30,
      primaryToolName: 'CapCut',
      primaryToolSlug: 'capcut',
      primaryToolLogoUrl: 'https://lf16-web-buz.capcut.com/obj/cap-web/common/icon.4a231734.svg',
      alternativeToolNames: ['Adobe Premiere', 'DaVinci Resolve'],
    },
    {
      stepOrder: 4,
      title: 'Thumbnail Generation',
      titleZh: '缩略图生成',
      description: 'Create eye-catching thumbnails',
      descriptionZh: '创建吸引眼球的缩略图',
      estimatedTime: 30,
      primaryToolName: 'Midjourney',
      primaryToolSlug: 'midjourney',
      primaryToolLogoUrl: 'https://cdn.worldvectorlogo.com/logos/midjourney.svg',
      alternativeToolNames: ['DALL-E', 'Stable Diffusion'],
    },
  ],
  // Add more workflow steps for other workflows...
}

// Extended tool costs for new workflows
export const extendedWorkflowToolCosts = {
  'viral-tweet-thread-generator': [
    {
      toolName: 'Perplexity',
      toolSlug: 'perplexity',
      toolLogoUrl: 'https://pplx-res.cloudinary.com/image/upload/v1705076612/website-assets/favicon-194x194_clneeu.png',
      planName: 'Pro',
      planNameZh: '专业版',
      monthlyPrice: 20,
      usageLimit: 'Unlimited searches',
      usageLimitZh: '无限搜索',
      isRequired: true,
      valueScore: 5,
    },
    {
      toolName: 'Claude',
      toolSlug: 'claude',
      toolLogoUrl: 'https://www.anthropic.com/images/icons/apple-touch-icon.png',
      planName: 'Pro',
      planNameZh: '专业版',
      monthlyPrice: 20,
      usageLimit: 'Priority access',
      usageLimitZh: '优先访问',
      isRequired: true,
      valueScore: 5,
    },
    {
      toolName: 'Canva',
      toolSlug: 'canva',
      toolLogoUrl: 'https://www.canva.com/favicon.ico',
      planName: 'Free',
      planNameZh: '免费版',
      monthlyPrice: 0,
      usageLimit: 'Basic features',
      usageLimitZh: '基础功能',
      isRequired: false,
      valueScore: 4,
    },
  ],
  'youtube-shorts-factory': [
    {
      toolName: 'Descript',
      toolSlug: 'descript',
      toolLogoUrl: 'https://www.descript.com/favicon.ico',
      planName: 'Creator',
      planNameZh: '创作者版',
      monthlyPrice: 15,
      usageLimit: '10 hours/month',
      usageLimitZh: '每月10小时',
      isRequired: true,
      valueScore: 5,
    },
    {
      toolName: 'Runway',
      toolSlug: 'runway',
      toolLogoUrl: 'https://assets-global.website-files.com/62e0e9ced95e1e13a67378a2/6304c0bf7e0b086647d7eb1f_favicon-256x256.png',
      planName: 'Standard',
      planNameZh: '标准版',
      monthlyPrice: 35,
      usageLimit: '625 credits/month',
      usageLimitZh: '每月625积分',
      isRequired: true,
      valueScore: 4,
    },
    {
      toolName: 'CapCut',
      toolSlug: 'capcut',
      toolLogoUrl: 'https://lf16-web-buz.capcut.com/obj/cap-web/common/icon.4a231734.svg',
      planName: 'Pro',
      planNameZh: '专业版',
      monthlyPrice: 15,
      usageLimit: 'All features',
      usageLimitZh: '所有功能',
      isRequired: false,
      valueScore: 4,
    },
    {
      toolName: 'Midjourney',
      toolSlug: 'midjourney',
      toolLogoUrl: 'https://cdn.worldvectorlogo.com/logos/midjourney.svg',
      planName: 'Basic',
      planNameZh: '基础版',
      monthlyPrice: 20,
      usageLimit: '200 images/month',
      usageLimitZh: '每月200张图片',
      isRequired: false,
      valueScore: 4,
    },
  ],
  // Add more tool costs for other workflows...
}